name: "OpenWrt SDK"

description: "Build OpenWrt packages via the SDK"

author: aparcar

runs:

  using: 'composite'

  steps:

    - run: docker build --build-arg ARCH -t sdk $GITHUB_ACTION_PATH

      shell: bash

    - run: |

        docker run --rm \

          --env BUILD_LOG \

          --env CONTAINER \

          --env EXTRA_FEEDS \

          --env FEEDNAME \

          --env GITHUB_WORKSPACE \

          --env IGNORE_ERRORS \

          --env KEY_BUILD \

          --env NO_DEFAULT_FEEDS \

          --env NO_REFRESH_CHECK \

          --env NO_SHFMT_CHECK \

          --env PACKAGES \

          --env V \

          --workdir /github/workspace \

          -v $(pwd):/github/workspace \

          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \

          sdk

      shell: bash


name: Test Build packages

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: aparcar/action-openwrt-sdk@composite
        env:
          ARCH: ${{ matrix.arch }}

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/packages/*.ipk
